### ISSUE TITLE
DDDD字幕勘误。

### ISSUE THREAD

**Issue by JER-ry** [op200/CheeseAni-SubRepository#23]
https://github.com/op200/CheeseAni-SubRepository/blob/9a6ab3e4c80dd6a9af1d7894e116cac37336ba9e/Subtitles/2024/DEAD%20DEAD%20DEMONS%20DEDEDEDE%20DESTRUCTION/00.zh-Hans.ass#L130

https://github.com/op200/CheeseAni-SubRepository/blob/9a6ab3e4c80dd6a9af1d7894e116cac37336ba9e/Subtitles/2024/DEAD%20DEAD%20DEMONS%20DEDEDEDE%20DESTRUCTION/00.zh-Hans.ass#L215

https://github.com/op200/CheeseAni-SubRepository/blob/9a6ab3e4c80dd6a9af1d7894e116cac37336ba9e/Subtitles/2024/DEAD%20DEAD%20DEMONS%20DEDEDEDE%20DESTRUCTION/00.zh-Hans.ass#L331

**Comment by JER-ry** [comment]
https://github.com/op200/CheeseAni-SubRepository/blob/9a6ab3e4c80dd6a9af1d7894e116cac37336ba9e/Subtitles/2024/DEAD%20DEAD%20DEMONS%20DEDEDEDE%20DESTRUCTION/01.zh-Hans.ass#L59

https://github.com/op200/CheeseAni-SubRepository/blob/9a6ab3e4c80dd6a9af1d7894e116cac37336ba9e/Subtitles/2024/DEAD%20DEAD%20DEMONS%20DEDEDEDE%20DESTRUCTION/01.zh-Hans.ass#L95

**Comment by op200** [comment]
已修改
感谢反馈
